// `.env.ts` is generated by the `npm run env` command
import env from '@env/.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://localhost:8080',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'it-IT']
};
